"use client";
import { StorageClient } from "@supabase/storage-js";
import { useMemo, useRef, useState } from "react";
import { readAdminImageZip } from "../bulk-import/admin-client-image-zip-reader";
import type { AdminDraftImageAsset } from "../model/admin-question-types";
import type { AdminTestImageBulkUploadResponse } from "../model/admin-test-image-bulk-upload-types";
import { ADMIN_TEST_IMAGE_MAX_BYTES, inspectAdminTestImage } from "../model/admin-test-image-validation";
import styles from "./admin-audio-zip-bulk-importer.module.css";

export interface AdminImageZipTarget { readonly questionId:string; readonly label:string; readonly image:AdminDraftImageAsset|null; readonly zipFileStem?:string; readonly defaultAlt?:string; }
interface Prepared {readonly clientId:string;readonly questionId:string;readonly label:string;readonly fileName:string;readonly bytes:Uint8Array;readonly mimeType:string;readonly sizeBytes:number;readonly width:number|null;readonly height:number|null;readonly alt:string;}
interface Analysis {readonly fileName:string;readonly prepared:readonly Prepared[];readonly totalBytes:number;readonly replacementCount:number;}
interface Props {readonly draftId:string;readonly targets:readonly AdminImageZipTarget[];readonly disabled?:boolean;readonly disabledReason?:string|null;readonly onApply:(updates:readonly {readonly questionId:string;readonly image:AdminDraftImageAsset}[])=>void;readonly onQueueStorageRemoval:(questionId:string,storagePath:string)=>void;}
const BULK_ENDPOINT="/api/admin/test-drafts/images/bulk", SINGLE_ENDPOINT="/api/admin/test-drafts/images", MAX_PARALLEL_UPLOADS=3;
function stem(name:string){const n=name.trim().replace(/\.(?:png|jpe?g|webp)$/iu,"").toLocaleLowerCase("uz").replace(/[ _]+/gu,"-").replace(/-{2,}/gu,"-");const m=n.match(/^q0*([1-9]\d*)$/u);return m?.[1]?`q${String(Number(m[1])).padStart(2,"0")}`:(n||null);}
function expected(s:string){return `${s}.png`;} function bytesText(n:number){return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(2)} MB`;}
async function json<T>(r:Response):Promise<T>{try{return await r.json() as T;}catch{throw new Error("Server javobini o‘qib bo‘lmadi.");}}
async function cleanup(draftId:string,items:readonly {questionId:string;storagePath:string}[]){await Promise.allSettled(items.map(i=>fetch(SINGLE_ENDPOINT,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({draftId,questionId:i.questionId,storagePath:i.storagePath})})));}
async function concurrent<T>(items:readonly T[],worker:(i:T)=>Promise<void>){let next=0,error:unknown=null;async function run(){while(error===null){const i=next++;if(i>=items.length)return;try{await worker(items[i] as T);}catch(e){error=e;return;}}}await Promise.all(Array.from({length:Math.min(MAX_PARALLEL_UPLOADS,items.length)},run));if(error)throw error;}
export function AdminImageZipBulkImporter({draftId,targets,disabled=false,disabledReason=null,onApply,onQueueStorageRemoval}:Props){
 const inputRef=useRef<HTMLInputElement|null>(null); const [busy,setBusy]=useState(false),[analysis,setAnalysis]=useState<Analysis|null>(null),[feedback,setFeedback]=useState<{type:"success"|"error";message:string}|null>(null),[progress,setProgress]=useState(0);
 const byStem=useMemo(()=>{const m=new Map<string,AdminImageZipTarget>();targets.forEach((t,i)=>{const s=stem(t.zipFileStem??`q${String(i+1).padStart(2,"0")}`);if(s&&!m.has(s))m.set(s,t);});return m;},[targets]);
 async function analyze(file:File|null){setAnalysis(null);setFeedback(null);setProgress(0);if(!file)return;if(disabled){setFeedback({type:"error",message:disabledReason??"Hozir rasm ZIP yuklab bo‘lmaydi."});return;}setBusy(true);try{const entries=await readAdminImageZip(file),found=new Set<string>(),prepared:Prepared[]=[],unknown:string[]=[];for(const entry of entries){const s=stem(entry.baseName),target=s?byStem.get(s):undefined;if(!s||!target){unknown.push(entry.baseName);continue;}if(found.has(s))throw new Error(`${entry.baseName}: bir savol rasmi takrorlangan.`);found.add(s);if(entry.bytes.byteLength>ADMIN_TEST_IMAGE_MAX_BYTES)throw new Error(`${entry.baseName}: rasm hajmi 5 MB dan oshmasligi kerak.`);const inspect=inspectAdminTestImage(entry.bytes,"");prepared.push({clientId:`bulk-${s}`,questionId:target.questionId,label:target.label,fileName:entry.baseName,bytes:entry.bytes,mimeType:inspect.mimeType,sizeBytes:entry.bytes.byteLength,width:inspect.width,height:inspect.height,alt:target.defaultAlt??`${target.label} diagrammasi`});}
 const missing=targets.map((t,i)=>stem(t.zipFileStem??`q${String(i+1).padStart(2,"0")}`)).filter((s):s is string=>s !== null && !found.has(s)).map(expected);if(unknown.length)throw new Error(`ZIP ichida savolga mos kelmagan rasm bor: ${unknown.slice(0,5).join(", ")}. Kutilgan: q01.png, q02.png ...`);if(missing.length||prepared.length!==targets.length)throw new Error(`Rasm soni mos emas. Kutilgan: ${targets.length}. Yetishmaydi: ${missing.slice(0,12).join(", ")||"yo‘q"}.`);prepared.sort((a,b)=>targets.findIndex(t=>t.questionId===a.questionId)-targets.findIndex(t=>t.questionId===b.questionId));setAnalysis({fileName:file.name,prepared,totalBytes:prepared.reduce((s,x)=>s+x.sizeBytes,0),replacementCount:targets.filter(t=>Boolean(t.image?.storagePath)).length});setFeedback({type:"success",message:`${prepared.length}/${targets.length} rasm to‘g‘ri moslandi.`});}catch(e){setFeedback({type:"error",message:e instanceof Error?e.message:"Rasm ZIP’ni tekshirib bo‘lmadi."});if(inputRef.current)inputRef.current.value="";}finally{setBusy(false);}}
 async function uploadAll(){if(!analysis||disabled)return;setBusy(true);setProgress(0);setFeedback(null);const uploaded:{questionId:string;storagePath:string}[]=[];try{const response=await fetch(BULK_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({draftId,files:analysis.prepared.map(x=>({clientId:x.clientId,questionId:x.questionId,fileName:x.fileName,mimeType:x.mimeType,sizeBytes:x.sizeBytes,width:x.width,height:x.height,alt:x.alt,caption:null}))})});const result=await json<AdminTestImageBulkUploadResponse>(response);if(!response.ok||result.status==="error")throw new Error(result.status==="error"?result.message:"Bulk rasm upload manzili yaratilmadi.");const sources=new Map(analysis.prepared.map(x=>[x.clientId,x]));await concurrent(result.items,async item=>{const source=sources.get(item.clientId);if(!source)throw new Error("Bulk rasm mapping buzildi.");const storage=new StorageClient(item.upload.storageUrl,{});const copy=new Uint8Array(source.bytes.byteLength);copy.set(source.bytes);const {error}=await storage.from(item.upload.bucket).uploadToSignedUrl(item.upload.path,item.upload.token,new Blob([copy.buffer],{type:item.image.mimeType}),{cacheControl:"3600",contentType:item.image.mimeType});if(error)throw new Error(`${source.fileName}: Storage upload xatosi — ${error.message}`);uploaded.push({questionId:item.questionId,storagePath:item.upload.path});setProgress(v=>v+1);});const updates=result.items.map(i=>({questionId:i.questionId,image:i.image}));targets.forEach(t=>{const u=updates.find(x=>x.questionId===t.questionId);if(u&&t.image?.storagePath&&t.image.storagePath!==u.image.storagePath)onQueueStorageRemoval(t.questionId,t.image.storagePath);});onApply(updates);setAnalysis(null);if(inputRef.current)inputRef.current.value="";setFeedback({type:"success",message:`${updates.length} ta rasm yuklandi va savollarga bog‘landi. Endi “Draftni saqlash”ni bosing.`});}catch(e){if(uploaded.length)await cleanup(draftId,uploaded);setFeedback({type:"error",message:e instanceof Error?`${e.message} Yuklangan yangi rasmlar rollback qilindi.`:"Bulk rasm yuklashda xatolik."});}finally{setBusy(false);}}
 return <section className={styles.importer} aria-labelledby="image-zip-import-title"><div className={styles.header}><div><span className={styles.eyebrow}>IMAGE ZIP BULK IMPORT</span><h2 id="image-zip-import-title">Savol rasmlarini bitta ZIP bilan yuklash</h2><p><strong>1 SAVOL = 1 RASM.</strong> Fayllar <strong>q01.png, q02.png ...</strong> bo‘lsin. q1.png va q01.png bir xil savol hisoblanadi. PNG/JPG/JPEG/WebP qabul qilinadi.</p></div><div className={styles.badge}>{targets.length} RASM</div></div><div className={styles.controls}><label className={styles.fileField}><span>Rasm ZIP</span><input ref={inputRef} type="file" accept=".zip,application/zip,application/x-zip-compressed" disabled={busy||disabled||targets.length===0} onChange={e=>{void analyze(e.target.files?.[0]??null);}}/></label><button type="button" className={styles.uploadButton} disabled={busy||disabled||!analysis} onClick={()=>{void uploadAll();}}>{busy&&analysis?`Yuklanmoqda ${progress}/${analysis.prepared.length}`:analysis?`${analysis.prepared.length} ta rasmni yuklash`:"Avval ZIP’ni tekshiring"}</button></div>{disabled&&disabledReason?<div className={styles.warning}>{disabledReason}</div>:null}{analysis?<div className={styles.analysisCard}><div className={styles.analysisSummary}><div><span>ZIP</span><strong>{analysis.fileName}</strong></div><div><span>Moslandi</span><strong>{analysis.prepared.length}/{targets.length}</strong></div><div><span>Umumiy hajm</span><strong>{bytesText(analysis.totalBytes)}</strong></div><div><span>Almashtiriladi</span><strong>{analysis.replacementCount}</strong></div></div><div className={styles.mappingList}>{analysis.prepared.map(x=><div className={styles.mappingRow} key={x.questionId}><span className={styles.ok}>✓</span><strong>{x.fileName}</strong><span>→</span><span>{x.label}</span><small>{bytesText(x.sizeBytes)}</small></div>)}</div></div>:null}{feedback?<div className={feedback.type==="error"?styles.error:styles.success} role="status">{feedback.message}</div>:null}<small>Har rasm 5 MB gacha. ZIP 120 MB gacha. Yuklangach “Draftni saqlash” majburiy.</small></section>;
}
